=== vaitameti/XML-data/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="screensize">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute type="xs:string" name="size" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="resolution">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="resolve" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="refreshRate">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute type="xs:string" name="frequency" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="gpu_type">
    <xs:simpleType>

      <!--custom restriction 1-->
      <xs:restriction base="xs:string">
        <xs:enumeration value="integrated"/>
        <xs:enumeration value="discrete"/>
        <xs:enumeration value="n/a"/>
      </xs:restriction>

    </xs:simpleType>
  </xs:element>
  <xs:element name="gpu_name"/>
  <xs:element name="gpu_model"/>
  <xs:element name="cpu_name">
    <xs:simpleType>
      <!--custom restriction 2-->
      <xs:restriction base="xs:string">
        <xs:enumeration value="Intel"/>
        <xs:enumeration value="AMD"/>
        <xs:enumeration value="Nvidia"/>
      </xs:restriction>

    </xs:simpleType>
  </xs:element>
  <xs:element name="cpu_model"/>
  <xs:element name="RAM_size">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute type="xs:string" name="byte" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="RAM_type">
    <xs:simpleType>

      <!--custom restriction 3-->
      <xs:restriction base="xs:string">
        <xs:pattern value="[D][D][R][1-4]"/>
      </xs:restriction>

    </xs:simpleType>
  </xs:element>
  <xs:element name="memory_frequency">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute type="xs:string" name="frequency" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="storage_capacity">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute type="xs:string" name="byte" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="storage_type">
    <xs:simpleType>

      <!--custom restriction 4-->
      <xs:restriction base="xs:string">
        <xs:enumeration value="SSD"/>
        <xs:enumeration value="HDD"/>
        <xs:enumeration value="SSD and HDD"/>
      </xs:restriction>

    </xs:simpleType>
  </xs:element>
  <xs:element name="width">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute type="xs:string" name="milimeter" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="height">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute type="xs:string" name="milimeter" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="battery_size">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute type="xs:string" name="ampere" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="charging_power">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute type="xs:string" name="power" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="charge_duration">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute type="xs:string" name="time" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="value">
    <xs:simpleType>

      <!--custom restriction 5-->
      <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0"></xs:minInclusive>
        <xs:maxExclusive value="500000"></xs:maxExclusive>
      </xs:restriction>

    </xs:simpleType>
  </xs:element>
  <xs:element name="currency">
    <xs:simpleType>

      <!--custom restriction 6-->
      <xs:restriction base="xs:string">
        <xs:length value="3"/>
        <xs:enumeration value="CZK"/>
        <xs:enumeration value="USD"/>
        <xs:enumeration value="EUR"/>
        <xs:enumeration value="YEN"/>
      </xs:restriction>

    </xs:simpleType>
  </xs:element>
  <xs:element name="discount">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="percent" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="discounted_value"/>
  <xs:element name="price">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="value" minOccurs="0"/>
        <xs:element ref="discount" minOccurs="0"/>
        <xs:element ref="discounted_value" minOccurs="0"/>
        <xs:element ref="currency"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="type" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="display">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="screensize"/>
        <xs:element ref="resolution"/>
        <xs:element ref="refreshRate"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="gpu">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="gpu_type"/>
        <xs:element ref="gpu_name"/>
        <xs:element ref="gpu_model"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="cpu">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cpu_name"/>
        <xs:element ref="cpu_model"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="system_memory">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="RAM_size"/>
        <xs:element ref="RAM_type"/>
        <xs:element ref="memory_frequency"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="storage">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="storage_capacity"/>
        <xs:element ref="storage_type"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dimensions">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="width"/>
        <xs:element ref="height"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="charging">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="battery_size"/>
        <xs:element ref="charging_power"/>
        <xs:element ref="charge_duration"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="weight">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="kilo" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="prices">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="price" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="company_name"/>
  <xs:element name="model"/>
  <xs:element name="detail">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="display"/>
        <xs:element ref="gpu"/>
        <xs:element ref="cpu"/>
        <xs:element ref="system_memory"/>
        <xs:element ref="storage"/>
        <xs:element ref="dimensions"/>
        <xs:element ref="charging"/>
        <xs:element ref="weight"/>
        <xs:element ref="prices"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="company">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="company_name"/>
        <xs:element ref="model"/>
        <xs:element ref="detail"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="laptops">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="company" maxOccurs="unbounded" minOccurs="5"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== vaitameti/XML-data/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<laptops xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="data.xsd">
    <company>
        <company_name>Dell</company_name>
        <model>Inspiron 15</model>
        <detail>
            <display>
                <screensize size="inch">15.6</screensize>
                <resolution resolve="pixel">1920*1080</resolution>
                <refreshRate frequency="Hz">60</refreshRate>
            </display>
            <gpu>
                <gpu_type>integrated</gpu_type>
                <gpu_name>Nvidia</gpu_name>
                <gpu_model>GeForce MX350</gpu_model>
            </gpu>
            <cpu>
                <cpu_name>Intel</cpu_name>
                <cpu_model>i7-1165G7</cpu_model>
            </cpu>
            <system_memory>
                <RAM_size byte="GB">12</RAM_size>
                <RAM_type>DDR4</RAM_type>
                <memory_frequency frequency="GHz">2.4</memory_frequency>
            </system_memory>
            <storage>
                <storage_capacity byte="GB">1024</storage_capacity>
                <storage_type>SSD</storage_type>
            </storage>
            <dimensions>
                <width milimeter="mm">356.1</width>
                <height milimeter="mm">17.9</height>
            </dimensions>
            <charging>
                <battery_size ampere="mAh">4200</battery_size>
                <charging_power power="W">65</charging_power>
                <charge_duration time="h">9</charge_duration>
            </charging>
            <weight kilo="kg">2.36</weight>
            <prices>
                <price type="normal">
                    <value>25000</value>
                    <currency>CZK</currency>
                </price>
                <price type="discounted">
                    <discount percent="%">15</discount>
                    <discounted_value>21250</discounted_value>
                    <currency>CZK</currency>
                </price>
            </prices>
        </detail>
    </company>
    <company>
        <company_name>MSI</company_name>
        <model>GF75 thin 9SCXR</model>
        <detail>
            <display>
                <screensize size="inch">17.3</screensize>
                <resolution resolve="pixel">1920*1080</resolution>
                <refreshRate frequency="Hz">120</refreshRate>
            </display>
            <gpu>
                <gpu_type>discrete</gpu_type>
                <gpu_name>Nvidia</gpu_name>
                <gpu_model>GeForce GTX 1650</gpu_model>
            </gpu>
            <cpu>
                <cpu_name>Intel</cpu_name>
                <cpu_model>i7-92345</cpu_model>
            </cpu>
            <system_memory>
                <RAM_size byte="GB">32</RAM_size>
                <RAM_type>DDR4</RAM_type>
                <memory_frequency frequency="GHz">2.6</memory_frequency>
            </system_memory>
            <storage>
                <storage_capacity byte="GB">1024</storage_capacity>
                <storage_type>HDD</storage_type>
            </storage>
            <dimensions>
                <width milimeter="mm">390.1</width>
                <height milimeter="mm">20.9</height>
            </dimensions>
            <charging>
                <battery_size ampere="mAh">4800</battery_size>
                <charging_power power="W">150</charging_power>
                <charge_duration time="h">8</charge_duration>
            </charging>
            <weight kilo="kg">2.2</weight>
            <prices>
                <price type="normal">
                    <value>24900</value>
                    <currency>CZK</currency>
                </price>
                <price type="discounted">
                    <discount percent="%">5</discount>
                    <discounted_value>23655</discounted_value>
                    <currency>CZK</currency>
                </price>
            </prices>
        </detail>
    </company>
    <company>
        <company_name>Lenovo</company_name>
        <model>legion 5</model>
        <detail>
            <display>
                <screensize size="inch">16</screensize>
                <resolution resolve="pixel">2560*1600</resolution>
                <refreshRate frequency="Hz">165</refreshRate>
            </display>
            <gpu>
                <gpu_type>discrete</gpu_type>
                <gpu_name>Nvidia</gpu_name>
                <gpu_model>GeForce RTX 3070</gpu_model>
            </gpu>
            <cpu>
                <cpu_name>AMD</cpu_name>
                <cpu_model>ryzen 7</cpu_model>
            </cpu>
            <system_memory>
                <RAM_size byte="GB">16</RAM_size>
                <RAM_type>DDR4</RAM_type>
                <memory_frequency frequency="GHz">4.3</memory_frequency>
            </system_memory>
            <storage>
                <storage_capacity byte="GB">512</storage_capacity>
                <storage_type>SSD</storage_type>
            </storage>
            <dimensions>
                <width milimeter="mm">382.1</width>
                <height milimeter="mm">21.9</height>
            </dimensions>
            <charging>
                <battery_size ampere="mAh">5200</battery_size>
                <charging_power power="W">160</charging_power>
                <charge_duration time="h">6</charge_duration>
            </charging>
            <weight kilo="kg">2.5</weight>
            <prices>
                <price type="normal">
                    <value>38000</value>
                    <currency>CZK</currency>
                </price>
                <price type="discounted">
                    <discount percent="%">10</discount>
                    <discounted_value>34200</discounted_value>
                    <currency>CZK</currency>
                </price>
            </prices>
        </detail>

    </company>
    <company>
        <company_name>Asus</company_name>
        <model>Zenbook 14</model>
        <detail>
            <display>
                <screensize size="inch">14</screensize>
                <resolution resolve="pixel">1920*1080</resolution>
                <refreshRate frequency="Hz">60</refreshRate>
            </display>
            <gpu>
                <gpu_type>integrated</gpu_type>
                <gpu_name>AMD</gpu_name>
                <gpu_model>Radeon Vega 7</gpu_model>
            </gpu>
            <cpu>
                <cpu_name>AMD</cpu_name>
                <cpu_model>ryzen 5</cpu_model>
            </cpu>
            <system_memory>
                <RAM_size byte="GB">16</RAM_size>
                <RAM_type>DDR3</RAM_type>
                <memory_frequency frequency="GHz">3.2</memory_frequency>
            </system_memory>
            <storage>
                <storage_capacity byte="GB">1024</storage_capacity>
                <storage_type>SSD</storage_type>
            </storage>
            <dimensions>
                <width milimeter="mm">374.1</width>
                <height milimeter="mm">19.9</height>
            </dimensions>
            <charging>
                <battery_size ampere="mAh">6000</battery_size>
                <charging_power power="W">67</charging_power>
                <charge_duration time="h">10</charge_duration>
            </charging>
            <weight kilo="kg">1.3</weight>
            <prices>
                <price type="normal">
                    <value>25000</value>
                    <currency>CZK</currency>
                </price>
                <price type="discounted">
                    <discount percent="%">20</discount>
                    <discounted_value>20720</discounted_value>
                    <currency>CZK</currency>
                </price>
            </prices>
        </detail>
    </company>
    <company>

        <company_name>HP</company_name>
        <model>EliteBook G8</model>
        <detail>
            <display>
                <screensize size="inch">15.6</screensize>
                <resolution resolve="pixel">1920*1080</resolution>
                <refreshRate frequency="Hz">60</refreshRate>
            </display>
            <gpu>
                <gpu_type>integrated</gpu_type>
                <gpu_name>AMD</gpu_name>
                <gpu_model>Radeon graphics</gpu_model>
            </gpu>
            <cpu>
                <cpu_name>AMD</cpu_name>
                <cpu_model>ryzen 7</cpu_model>
            </cpu>
            <system_memory>
                <RAM_size byte="GB">16</RAM_size>
                <RAM_type>DDR4</RAM_type>
                <memory_frequency frequency="GHz">3.2</memory_frequency>
            </system_memory>
            <storage>
                <storage_capacity byte="GB">512</storage_capacity>
                <storage_type>SSD</storage_type>
            </storage>
            <dimensions>
                <width milimeter="mm">359.6</width>
                <height milimeter="mm">19.2</height>
            </dimensions>
            <charging>
                <battery_size ampere="mAh">4500</battery_size>
                <charging_power power="W">65</charging_power>
                <charge_duration time="h">7</charge_duration>
            </charging>
            <weight kilo="kg">1.7</weight>
            <prices>
                <price type="normal">
                    <value>37000</value>
                    <currency>CZK</currency>
                </price>
                <price type="discounted">
                    <discount percent="%">20</discount>
                    <discounted_value>29600</discounted_value>
                    <currency>CZK</currency>
                </price>
            </prices>
        </detail>
    </company>
</laptops>
